export const dynamic = "force-dynamic"; // Ensures full SSR
import { Outfit } from "next/font/google";
import Dynamic from 'next/dynamic'
import "./globals.css";
import Script from 'next/script';
import Head from 'next/head';

// ----------------------------------------------------------------

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Add required weights as needed
});

// export const metadata = {
//   title: "Immobilien Suche",
//   description: "Generated by create next app",
// };

export async function generateMetadata() {
  return {
    title: "Immobilien Suche",
    description: "Generated by create next app",
  };
}

const Header = Dynamic(() => import('../component/header'), { ssr: true })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Load only UIKit CSS for icons */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.23.1/dist/css/uikit.min.css" />
        {/* <Script src="uikit/dist/js/uikit-icons.min.js" /> */}
        <Script src="https://cdn.jsdelivr.net/npm/uikit@3.23.1/dist/js/uikit.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/uikit@3.23.1/dist/js/uikit-icons.min.js" />

      </Head>
      <body
        className={`${outfit.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
